/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface JsonAutobuildTable {
        "apiurl": string;
        "columns": string;
        "filters": string;
        "headers": string;
        "limitqueryparameter": string;
        "offsetqueryparameter": string;
        "totalparameter": string;
    }
}
declare global {
    interface HTMLJsonAutobuildTableElement extends Components.JsonAutobuildTable, HTMLStencilElement {
    }
    var HTMLJsonAutobuildTableElement: {
        prototype: HTMLJsonAutobuildTableElement;
        new (): HTMLJsonAutobuildTableElement;
    };
    interface HTMLElementTagNameMap {
        "json-autobuild-table": HTMLJsonAutobuildTableElement;
    }
}
declare namespace LocalJSX {
    interface JsonAutobuildTable {
        "apiurl": string;
        "columns"?: string;
        "filters"?: string;
        "headers"?: string;
        "limitqueryparameter"?: string;
        "offsetqueryparameter"?: string;
        "totalparameter"?: string;
    }
    interface IntrinsicElements {
        "json-autobuild-table": JsonAutobuildTable;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "json-autobuild-table": LocalJSX.JsonAutobuildTable & JSXBase.HTMLAttributes<HTMLJsonAutobuildTableElement>;
        }
    }
}
